Pavel kirienko patch 1
Zubax/dronecode_probe pull request #3
Opened 2019-03-22 10:43 UTC by dimracer

2019-03-22 16:17 UTC, pavel-kirienko requested changes

2019-03-22 16:17 UTC, pavel-kirienko commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
Зачем команду дублировать? И так понятно что аргументы нужно подставить какие следует.
```suggestion
```

2019-03-22 16:17 UTC, pavel-kirienko commented on MANUFACTURING.md
> +It is adviced to use the following tool for flashing: <https://github.com/Zubax/zubax_serial_updater>.
Это должно быть в следующем пункте. Ещё тут моя опечатка, правильно `advised`.

2019-03-22 16:17 UTC, pavel-kirienko commented on MANUFACTURING.md
> +1. Connect the board to USB and SWD pins of the board to any other SWD adapter (e.g., another Dronecode Probe).
```suggestion
1. Connect the target board to the computer via USB; connect its SWD pins to any other SWD adapter
(e.g., another Dronecode Probe).
```

2019-03-22 16:17 UTC, pavel-kirienko commented on MANUFACTURING.md
> +SWD pins are marked on the bottom side of the board: SWD, GND, SWC, 5V. Note, that 5V pin is target voltage probe pin. Don't connect it to any power supply.
```suggestion
The SWD signals are marked on the bottom side of the board: `SWD`, `GND`, `SWC`, `5V`.
Note that the pin marked `5V` is the target voltage sensing pin (not a power supply input).
```

2019-03-22 16:20 UTC, dimracer commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
Не всем понятно. Это же для производственников файл, как я понимаю, не для разработчиков. Для производственников нужно стараться вообще свести к минимуму действия "по умолчанию", должны быть расписаны все операции

2019-03-22 16:21 UTC, pavel-kirienko commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
Это понятно всем, кто умеет читать; в крайнем случае мы просто отправим им готовый elf.

2019-03-22 16:23 UTC, dimracer commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
Ну что плохого если это будет в этом файле? что эта строчка сильно перегружает документ?

2019-03-22 16:26 UTC, pavel-kirienko commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
Конкретно в этой строчке большой проблемы нет. Просто излишне подробную документацию поддерживать сложнее; со временем детали могут устареть, сделав документацию недействительной. Ошибочная документация куда хуже, чем полностью отсутствующая, поэтому важен баланс. Хорошая документация описывает не последовательность действий, а ключевые концепции, предоставляя читателю досмыслить остальное самостоятельно.

2019-03-22 16:36 UTC, dimracer commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
@j3qq4hch ну скажите  Вы что-нибудь. Я точно знаю, что производственники споткнутся при отсутсвии этой строчки и будут нас дергать.

2019-03-22 20:56 UTC, pavel-kirienko commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
Вообще, если отложить вопрос надобности этой строчки (надобности нет), зачем создавать elf из образа прошивки, ведь для загрузки через бутлоадер нужен бинарник?

2019-03-22 21:53 UTC, eugeny-stoyka commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
*ем попкорн*

2019-03-22 21:55 UTC, pavel-kirienko commented
Не подавись.

On Fri, Mar 22, 2019, 23:53 Eugeny Stoyka <notifications@github.com> wrote:

> *@eugeny-stoyka* commented on this pull request.
> ------------------------------
>
> In MANUFACTURING.md
> <https://github.com/Zubax/dronecode_probe/pull/3#discussion_r268351091>:
>
> >
>
>  Prebuilt binaries can be found here: <https://files.zubax.com/products/dronecode_probe>.
>
>
>
> +The following comands can be used to create a loadable ELF from a flat binary:
>
> +
>
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic_dfu.bin blackmagic_dfu.elf
>
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
>
>
> *ем попкорн*
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Zubax/dronecode_probe/pull/3#discussion_r268351091>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADJUZAn0zWyzhApyVEC5SMdS1QnFEqv5ks5vZVDPgaJpZM4cDS2Z>
> .
>

2019-03-24 19:29 UTC, ctech4285 commented
Looks good to me

2019-03-25 16:36 UTC, dimracer commented on MANUFACTURING.md
> +    arm-none-eabi-objcopy -I binary -O elf32-little --change-section-address .data=0x08000000 blackmagic.bin blackmagic.elf
Да, для загрузки чере serial нужен бинарник. Но если прошивать другим DCP через SWD нужен elf.

2019-03-25 16:45 UTC, merged